### ISSUE TITLE
RAML queryParameter naming

### ISSUE THREAD

**Issue by burrbd** [EconomistDigitalSolutions/ramlapi#14]
``` yaml
    queryParameters:
      country:
        name: Country
        type: string
        description: User country code
        example: GB
        required: true
        pattern: "[a-z]{2}"
```

RAML spec does not support the name property (listed above). `raml`/`ramlapi` package uses name property for query parameter key. Should use the actual RAML key -- **country** (not **Country**).
